### ISSUE TITLE
Is there any tips for download the QM9 Electron density functions? + Can you provide some preprocess codes for Cubic dataset? + etcs

### ISSUE THREAD

**Issue by seongsukim-ml** [ccr-cheng/InfGCN-pytorch#3]
Hello.

First of all, thank you for sharing your great work. I was impressed by your work and tried to reproduce your work to get insights.

But in the reproducing sequence, I had some troubles and wanted to ask about it.

1)

When I tried to download the QM9 EDF dataset in the figshares, it was about 1T and ETA was about 6 days in  my Linux systems.

In the downloading sequence, I used `wget` in the terminal but it was irregularly disconnected and started from the bottom.

Do you have any tips for downloading the QM9 EDF dataset?

2)

And I downloaded the Cubit datasets from Figshares but the number of the samples in the whole dataset(ECD-database-part1,2,3) was 17418.

However, in your paper, you used the 16421 dataset as shown in Appendix C.

Could you provide the list of the train/val/test split name or code to divide and read the dataset? I was stuck in the dataset split process.

3)

Finally, I got the reproduced results of ethane and malonaldehyde of the QM9. The results show that MAE as shown below:

Ethane with seed 42
![image](https://github.com/ccr-cheng/InfGCN-pytorch/assets/46878412/0eb7d01e-4f6b-466e-b738-070006d3d00a)

Malonaldehyde with seed 42
![image](https://github.com/ccr-cheng/InfGCN-pytorch/assets/46878412/ace4eab4-26e7-48c7-b27d-c8423e5010c1)

In the training metric, the final inference MAEs were about 0.12. Are these NMAE which was reported in the paper? I think it is quite different from the results in your main results.

So can you provide the seeds that you used in the paper or the pre-trained model for the MD? Or some detailed configuration of your model may be helpful, I am confused that I missed something.

Thank you.

---

```
# md_malon.yml
train:
  seed: 42 # default seed 42
  train_samples: 1024
  val_samples: 2048
  max_iter: 2000 # maximum iteration
  batch_size: 64
  log_freq: 10000
  val_freq: 20
  save_freq: 100
  max_grad_norm: 100.
  optimizer:
    type: adam
    lr: 5.e-3
    weight_decay: 0.
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.5
    patience: 5
    min_lr: 1.e-5

test:
  batch_size: 16
  inf_samples: 4096
  num_infer: null
  num_vis: 2

datasets:
  type: small_density
  root: ../dataset
  mol_name: malonaldehyde

model:
  type: infgcn
  n_atom_type: 3
  num_radial: 16
  num_spherical: 7
  radial_embed_size: 64
  radial_hidden_size: 128
  num_radial_layer: 2
  num_gcn_layer: 3
  cutoff: 3.
  grid_cutoff: 3.
  is_fc: false
  gauss_start: 0.5
  gauss_end: 5.
```
